### ISSUE TITLE
Error: Swimlane id is required

### ISSUE THREAD

**Issue by xet7** [wekan/wekan-gogs#6]
@andresmanelli 

I tested this:
1) Wekan Priority board and lists were created to Wekan successfully.
2) tried to add new issue to Gogs
3) Wekan-Gogs tried to add card to Wekan
4) Wekan gave this error message about Swimland id is required.

```
$ cd wekan
$ meteor
=> App running at: http://localhost:3000/
W20180406-14:07:31.769(3)? (STDERR) Error: Swimlane id is required
W20180406-14:07:31.770(3)? (STDERR)     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
W20180406-14:07:31.771(3)? (STDERR)     at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
W20180406-14:07:31.771(3)? (STDERR)     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
W20180406-14:07:31.771(3)? (STDERR)     at packages/matb33_collection-hooks.js:127:46
W20180406-14:07:31.772(3)? (STDERR)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
W20180406-14:07:31.772(3)? (STDERR)     at Object.directOp (packages/matb33_collection-hooks.js:47:27)
W20180406-14:07:31.773(3)? (STDERR)     at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
W20180406-14:07:31.773(3)? (STDERR)     at models/cards.js:493:31
W20180406-14:07:31.773(3)? (STDERR)     at packages/simple_json-routes.js:98:9
W20180406-14:08:54.965(3)? (STDERR) Error: Swimlane id is required
W20180406-14:08:54.966(3)? (STDERR)     at getErrorObject (packages/aldeed_collection2-core.js:480:15)
W20180406-14:08:54.966(3)? (STDERR)     at ns.Collection.doValidate (packages/aldeed_collection2-core.js:462:13)
W20180406-14:08:54.966(3)? (STDERR)     at ns.Collection.Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:214:25)
W20180406-14:08:54.967(3)? (STDERR)     at packages/matb33_collection-hooks.js:127:46
W20180406-14:08:54.969(3)? (STDERR)     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
W20180406-14:08:54.969(3)? (STDERR)     at Object.directOp (packages/matb33_collection-hooks.js:47:27)
W20180406-14:08:54.969(3)? (STDERR)     at Object.self.direct.(anonymous function) [as insert] (packages/matb33_collection-hooks.js:126:30)
W20180406-14:08:54.969(3)? (STDERR)     at models/cards.js:493:31
W20180406-14:08:54.970(3)? (STDERR)     at packages/simple_json-routes.js:98:9
```

I will also try to figure out if I can somehow add Swimlane id myself.

**Comment by xet7** [comment]
There is no swimlanes at all on those boards Wekan-Gogs created to Wekan.

I am also unable to add cards to those synced boards, add card button does not do anything.

**Comment by andresmanelli** [comment]
This is because the code doesn't create a default swimlane for the created boards. And then when a card is added via API, there is no swimlaneId in the request.

I am not sure right now if the Cards API supports swimlaneId in the request.

I'm quite busy at the moment, but I'll keep a mental note on this.

What should be needed:

1. Create `Swimlanes` key in `wekan_client.js`
2. Create defualt swimlane when creating boards
3. Add `swimlaneId` field to the card creation body
4. Update database accordingly

**Comment by andresmanelli** [comment]
I'm working on this.

**Comment by andresmanelli** [comment]
@xet7 Please see https://github.com/wekan/wekan/pull/1876 in order to get this fixed :D

**Comment by andresmanelli** [comment]
@xet7 If you have some time, It'd be nice to have some feedback. Thanks!
